# Generated by Django 3.1.3 on 2021-03-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_price', models.IntegerField()),
                ('room_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('BIKE', 'BIKE'), ('CAR', 'CAR'), ('ELECTRONIC', 'ELECTRONIC'), ('FURNITURE', 'FURNITURE'), ('HOUSING', 'HOUSING'), ('PHONE', 'PHONE')], default='bike', max_length=20),
        ),
    ]
